/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-playground-examples.ts
 * Run: pnpm run build-examples
 */

export interface ExampleMetadata {
  id: string;
  title: string;
  description?: string;
  tags: string[];
}

/**
 * Available example IDs
 */
export const exampleIds = [
  "basic-types",
  "enums-args",
  "interfaces",
  "mutations",
  "relay-plugin",
  "simple-objects-plugin",
  "unions",
  "with-input-plugin"
] as const;

/**
 * Example metadata (lightweight - no code content)
 */
export const exampleMetadata: ExampleMetadata[] = [
  {
    "id": "basic-types",
    "title": "Basic Types",
    "description": "Define object types and queries",
    "tags": []
  },
  {
    "id": "enums-args",
    "title": "Enums & Arguments",
    "description": "Define enums and use typed arguments",
    "tags": []
  },
  {
    "id": "interfaces",
    "title": "Interfaces & Unions",
    "description": "Using interfaces and union types",
    "tags": []
  },
  {
    "id": "mutations",
    "title": "Mutations",
    "description": "Define mutations with input types",
    "tags": []
  },
  {
    "id": "relay-plugin",
    "title": "Relay Plugin",
    "description": "Use the Relay plugin for cursor-based pagination and global IDs",
    "tags": []
  },
  {
    "id": "simple-objects-plugin",
    "title": "Simple Objects Plugin",
    "description": "Use the Simple Objects plugin to define objects without separate type definitions",
    "tags": []
  },
  {
    "id": "unions",
    "title": "Union Types",
    "description": "Define union types for polymorphic results",
    "tags": []
  },
  {
    "id": "with-input-plugin",
    "title": "With-Input Plugin",
    "description": "Use the With-Input plugin to easily define fields with a single input object",
    "tags": []
  }
];

/**
 * Get metadata for a specific example
 */
export function getExampleMetadata(id: string): ExampleMetadata | undefined {
  return exampleMetadata.find(e => e.id === id);
}
