// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:26621165d69ac72f42a5e328fd9b567c2913617adcd0fa89c1336dffa27fc5f4'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:16de9504cc97e95ba09948e5cb78650ff8a4cb084d4aef50d68bf6593e778289'>;
export type ProfileHash =
  ProfileHashBase<'sha256:213031a5ce861b455f22bc065769080ea0357fabcb999de0190524ecd32531f7'>;

export type CodecTypes = SqliteTypes;
export type OperationTypes = Record<string, never>;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Comment: {
    readonly id: CodecTypes['sql/char@1']['output'];
    readonly body: CodecTypes['sqlite/text@1']['output'];
    readonly authorId: CodecTypes['sql/char@1']['output'];
    readonly postId: CodecTypes['sql/char@1']['output'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
  };
  readonly Post: {
    readonly id: CodecTypes['sql/char@1']['output'];
    readonly title: CodecTypes['sqlite/text@1']['output'];
    readonly content: CodecTypes['sqlite/text@1']['output'];
    readonly published: CodecTypes['sqlite/integer@1']['output'];
    readonly authorId: CodecTypes['sql/char@1']['output'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
  };
  readonly User: {
    readonly id: CodecTypes['sql/char@1']['output'];
    readonly firstName: CodecTypes['sqlite/text@1']['output'];
    readonly lastName: CodecTypes['sqlite/text@1']['output'];
    readonly email: CodecTypes['sqlite/text@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Comment: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly body: CodecTypes['sqlite/text@1']['input'];
    readonly authorId: CodecTypes['sql/char@1']['input'];
    readonly postId: CodecTypes['sql/char@1']['input'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
  };
  readonly Post: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly title: CodecTypes['sqlite/text@1']['input'];
    readonly content: CodecTypes['sqlite/text@1']['input'];
    readonly published: CodecTypes['sqlite/integer@1']['input'];
    readonly authorId: CodecTypes['sql/char@1']['input'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
  };
  readonly User: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly firstName: CodecTypes['sqlite/text@1']['input'];
    readonly lastName: CodecTypes['sqlite/text@1']['input'];
    readonly email: CodecTypes['sqlite/text@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  OperationTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly comment: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly body: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly authorId: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly postId: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['authorId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly name: 'comment_authorId_fkey';
            readonly constraint: true;
            readonly index: true;
          },
          {
            readonly columns: readonly ['postId'];
            readonly references: { readonly table: 'post'; readonly columns: readonly ['id'] };
            readonly name: 'comment_postId_fkey';
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly post: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly content: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly published: {
            readonly nativeType: 'integer';
            readonly codecId: 'sqlite/integer@1';
            readonly nullable: false;
            readonly default: {
              readonly kind: 'literal';
              readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
            };
          };
          readonly authorId: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['authorId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly name: 'post_authorId_fkey';
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly user: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly firstName: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly lastName: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [{ readonly columns: readonly ['email'] }];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
    readonly storageHash: StorageHash;
  },
  {
    readonly Comment: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly body: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly postId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['authorId'];
            readonly targetFields: readonly ['id'];
          };
        };
        readonly post: {
          readonly to: 'Post';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['postId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: {
        readonly table: 'comment';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly body: { readonly column: 'body' };
          readonly authorId: { readonly column: 'authorId' };
          readonly postId: { readonly column: 'postId' };
          readonly createdAt: { readonly column: 'createdAt' };
        };
      };
    };
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly content: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly published: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['authorId'];
            readonly targetFields: readonly ['id'];
          };
        };
        readonly comments: {
          readonly to: 'Comment';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['postId'];
          };
        };
      };
      readonly storage: {
        readonly table: 'post';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly title: { readonly column: 'title' };
          readonly content: { readonly column: 'content' };
          readonly published: { readonly column: 'published' };
          readonly authorId: { readonly column: 'authorId' };
          readonly createdAt: { readonly column: 'createdAt' };
        };
      };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly firstName: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly lastName: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['authorId'];
          };
        };
        readonly comments: {
          readonly to: 'Comment';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['authorId'];
          };
        };
      };
      readonly storage: {
        readonly table: 'user';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly firstName: { readonly column: 'firstName' };
          readonly lastName: { readonly column: 'lastName' };
          readonly email: { readonly column: 'email' };
        };
      };
    };
  }
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: { readonly user: 'User'; readonly post: 'Post'; readonly comment: 'Comment' };
  readonly capabilities: {
    readonly sql: {
      readonly autoIndexesForeignKeys: false;
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'comment'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'post'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'user'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
