/**
 * Re-exports @pothos/core for use in the browser playground.
 * This file is used to provide the Pothos module to the execution engine.
 */

import SchemaBuilder, {
  ArgumentRef,
  BasePlugin,
  BaseTypeRef,
  BuildCache,
  BuiltinScalarRef,
  createInputValueMapper,
  EnumRef,
  FieldBuilder,
  FieldRef,
  ImplementableInputObjectRef,
  ImplementableInterfaceRef,
  ImplementableObjectRef,
  InputFieldBuilder,
  InputFieldRef,
  InputListRef,
  InputObjectRef,
  InputTypeRef,
  InterfaceFieldBuilder,
  InterfaceRef,
  ListRef,
  MutationFieldBuilder,
  MutationRef,
  mapInputFields,
  ObjectFieldBuilder,
  ObjectRef,
  OutputTypeRef,
  QueryFieldBuilder,
  QueryRef,
  RootFieldBuilder,
  ScalarRef,
  SubscriptionFieldBuilder,
  SubscriptionRef,
  UnionRef,
} from '@pothos/core';

export {
  ArgumentRef,
  BasePlugin,
  BaseTypeRef,
  BuildCache,
  BuiltinScalarRef,
  createInputValueMapper,
  EnumRef,
  FieldBuilder,
  FieldRef,
  ImplementableInputObjectRef,
  ImplementableInterfaceRef,
  ImplementableObjectRef,
  InputFieldBuilder,
  InputFieldRef,
  InputListRef,
  InputObjectRef,
  InputTypeRef,
  InterfaceFieldBuilder,
  InterfaceRef,
  ListRef,
  MutationFieldBuilder,
  MutationRef,
  mapInputFields,
  ObjectFieldBuilder,
  ObjectRef,
  OutputTypeRef,
  QueryFieldBuilder,
  QueryRef,
  RootFieldBuilder,
  ScalarRef,
  SchemaBuilder,
  SubscriptionFieldBuilder,
  SubscriptionRef,
  UnionRef,
};

export default SchemaBuilder;

export const pothosModule = {
  default: SchemaBuilder,
  SchemaBuilder,
  ArgumentRef,
  BasePlugin,
  BaseTypeRef,
  BuildCache,
  BuiltinScalarRef,
  EnumRef,
  FieldBuilder,
  FieldRef,
  ImplementableInputObjectRef,
  ImplementableInterfaceRef,
  ImplementableObjectRef,
  InputFieldBuilder,
  InputFieldRef,
  InputListRef,
  InputObjectRef,
  InputTypeRef,
  InterfaceFieldBuilder,
  InterfaceRef,
  ListRef,
  mapInputFields,
  createInputValueMapper,
  MutationFieldBuilder,
  MutationRef,
  ObjectFieldBuilder,
  ObjectRef,
  OutputTypeRef,
  QueryFieldBuilder,
  QueryRef,
  RootFieldBuilder,
  ScalarRef,
  SubscriptionFieldBuilder,
  SubscriptionRef,
  UnionRef,
};
