#!/usr/bin/env tsx

/**
 * Build script to bundle playground examples from separate files into a JSON bundle
 *
 * This script:
 * 1. Reads example directories from website/public/playground-examples/
 * 2. Loads schema.ts, query.graphql, and metadata.json from each example
 * 3. Bundles them into a single JSON file for dynamic loading
 * 4. Outputs to website/public/playground-examples.json
 */

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

interface ExampleFile {
  filename: string;
  content: string;
  language?: 'typescript' | 'graphql';
}

interface PlaygroundExample {
  id: string;
  title: string;
  description?: string;
  tags?: string[];
  files: ExampleFile[];
  defaultQuery: string;
  queries?: Array<{ title?: string; query: string; variables?: string }>;
}

interface ExampleMetadata {
  id: string;
  title: string;
  description?: string;
  tags?: string[];
}

const EXAMPLES_SOURCE_DIR = join(process.cwd(), 'playground-examples');
const EXAMPLES_OUTPUT_DIR = join(process.cwd(), 'public', 'playground-examples');
const INDEX_FILE = join(
  process.cwd(),
  'components',
  'playground',
  'examples',
  'examples-index.generated.ts',
);

async function buildExamples() {
  console.log('[Build Examples] Starting...');

  // Read all example directories
  const entries = await readdir(EXAMPLES_SOURCE_DIR, { withFileTypes: true });
  const exampleDirs = entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);

  console.log(`[Build Examples] Found ${exampleDirs.length} examples:`, exampleDirs);

  const examples: PlaygroundExample[] = [];

  for (const dirName of exampleDirs) {
    try {
      const examplePath = join(EXAMPLES_SOURCE_DIR, dirName);

      // Read metadata
      const metadataPath = join(examplePath, 'metadata.json');
      const metadataContent = await readFile(metadataPath, 'utf-8');
      const metadata: ExampleMetadata = JSON.parse(metadataContent);

      // Read all files in the example directory
      const exampleFiles = await readdir(examplePath, { withFileTypes: true });

      const files: ExampleFile[] = [];
      const queryFileInfo: Array<{ filename: string; content: string }> = [];

      for (const file of exampleFiles) {
        if (!file.isFile()) {
          continue;
        }

        const filename = file.name;

        // Skip metadata.json
        if (filename === 'metadata.json') {
          continue;
        }

        const filePath = join(examplePath, filename);
        const content = await readFile(filePath, 'utf-8');

        // Collect .ts files as code files
        if (filename.endsWith('.ts')) {
          files.push({
            filename,
            content,
            language: 'typescript',
          });
        }
        // Collect .graphql files as query files
        else if (filename.endsWith('.graphql')) {
          queryFileInfo.push({ filename, content });
        }
      }

      // Sort files to ensure schema.ts comes first if it exists
      files.sort((a, b) => {
        if (a.filename === 'schema.ts') {
          return -1;
        }
        if (b.filename === 'schema.ts') {
          return 1;
        }
        return a.filename.localeCompare(b.filename);
      });

      // Use first query file as default, or empty query
      const defaultQuery = queryFileInfo[0]?.content || '{\n  # Add your query here\n}';

      // Build queries array for multiple tabs
      const queries = queryFileInfo.map((fileInfo) => ({
        title: fileInfo.filename.replace(/\.(graphql|gql)$/, ''),
        query: fileInfo.content,
      }));

      const example: PlaygroundExample = {
        id: metadata.id,
        title: metadata.title,
        description: metadata.description,
        tags: metadata.tags,
        files,
        defaultQuery,
        queries: queries.length > 0 ? queries : undefined,
      };

      examples.push(example);
      console.log(
        `[Build Examples] ✓ Built ${metadata.id} (${files.length} code files, ${queryFileInfo.length} queries)`,
      );
    } catch (err) {
      console.error(`[Build Examples] ✗ Failed to build ${dirName}:`, err);
    }
  }

  // Sort examples by ID for consistency
  examples.sort((a, b) => a.id.localeCompare(b.id));

  // Ensure output directory exists
  await mkdir(EXAMPLES_OUTPUT_DIR, { recursive: true });

  // Write individual JSON bundles for each example to public directory
  for (const example of examples) {
    const bundlePath = join(EXAMPLES_OUTPUT_DIR, `${example.id}.json`);
    await writeFile(bundlePath, JSON.stringify(example, null, 2), 'utf-8');
  }

  // Generate TypeScript index file with example IDs and metadata
  const exampleIds = examples.map((e) => e.id);
  const exampleMetadata = examples.map((e) => ({
    id: e.id,
    title: e.title,
    description: e.description,
    tags: e.tags || [],
  }));

  const indexContent = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-playground-examples.ts
 * Run: pnpm run build-examples
 */

export interface ExampleMetadata {
  id: string;
  title: string;
  description?: string;
  tags: string[];
}

/**
 * Available example IDs
 */
export const exampleIds = ${JSON.stringify(exampleIds, null, 2)} as const;

/**
 * Example metadata (lightweight - no code content)
 */
export const exampleMetadata: ExampleMetadata[] = ${JSON.stringify(exampleMetadata, null, 2)};

/**
 * Get metadata for a specific example
 */
export function getExampleMetadata(id: string): ExampleMetadata | undefined {
  return exampleMetadata.find(e => e.id === id);
}
`;

  await writeFile(INDEX_FILE, indexContent, 'utf-8');

  console.log(`[Build Examples] ✓ Built ${examples.length} examples`);
  console.log(`[Build Examples] ✓ Index: ${INDEX_FILE}`);
  console.log('[Build Examples] Done!');
}

// Run
buildExamples().catch((err) => {
  console.error('[Build Examples] Fatal error:', err);
  process.exit(1);
});
